name: GunSystem
main: Main
version: 1.0.0
api: 3.0.0

permissions:
  GunSystem:
    default: false
    description: "ベース"
    children:
      Gun.Command:
        default: true
        description: "ガンシステム"